# city_data.py — ~935 US cities for local SEO landing pages
# Each entry: {"city": str, "state": str (full), "abbr": str (2-letter), "slug": str}

CITIES = [
    # Alabama
    {"city":"Birmingham","state":"Alabama","abbr":"AL","slug":"birmingham-al"},
    {"city":"Montgomery","state":"Alabama","abbr":"AL","slug":"montgomery-al"},
    {"city":"Huntsville","state":"Alabama","abbr":"AL","slug":"huntsville-al"},
    {"city":"Mobile","state":"Alabama","abbr":"AL","slug":"mobile-al"},
    {"city":"Tuscaloosa","state":"Alabama","abbr":"AL","slug":"tuscaloosa-al"},
    {"city":"Hoover","state":"Alabama","abbr":"AL","slug":"hoover-al"},
    {"city":"Dothan","state":"Alabama","abbr":"AL","slug":"dothan-al"},
    {"city":"Auburn","state":"Alabama","abbr":"AL","slug":"auburn-al"},
    {"city":"Decatur","state":"Alabama","abbr":"AL","slug":"decatur-al"},
    {"city":"Madison","state":"Alabama","abbr":"AL","slug":"madison-al"},
    # Alaska
    {"city":"Anchorage","state":"Alaska","abbr":"AK","slug":"anchorage-ak"},
    {"city":"Fairbanks","state":"Alaska","abbr":"AK","slug":"fairbanks-ak"},
    {"city":"Juneau","state":"Alaska","abbr":"AK","slug":"juneau-ak"},
    {"city":"Sitka","state":"Alaska","abbr":"AK","slug":"sitka-ak"},
    {"city":"Wasilla","state":"Alaska","abbr":"AK","slug":"wasilla-ak"},
    # Arizona
    {"city":"Phoenix","state":"Arizona","abbr":"AZ","slug":"phoenix-az"},
    {"city":"Tucson","state":"Arizona","abbr":"AZ","slug":"tucson-az"},
    {"city":"Mesa","state":"Arizona","abbr":"AZ","slug":"mesa-az"},
    {"city":"Chandler","state":"Arizona","abbr":"AZ","slug":"chandler-az"},
    {"city":"Scottsdale","state":"Arizona","abbr":"AZ","slug":"scottsdale-az"},
    {"city":"Glendale","state":"Arizona","abbr":"AZ","slug":"glendale-az"},
    {"city":"Gilbert","state":"Arizona","abbr":"AZ","slug":"gilbert-az"},
    {"city":"Tempe","state":"Arizona","abbr":"AZ","slug":"tempe-az"},
    {"city":"Peoria","state":"Arizona","abbr":"AZ","slug":"peoria-az"},
    {"city":"Surprise","state":"Arizona","abbr":"AZ","slug":"surprise-az"},
    {"city":"Yuma","state":"Arizona","abbr":"AZ","slug":"yuma-az"},
    {"city":"Avondale","state":"Arizona","abbr":"AZ","slug":"avondale-az"},
    {"city":"Flagstaff","state":"Arizona","abbr":"AZ","slug":"flagstaff-az"},
    {"city":"Goodyear","state":"Arizona","abbr":"AZ","slug":"goodyear-az"},
    {"city":"Buckeye","state":"Arizona","abbr":"AZ","slug":"buckeye-az"},
    # Arkansas
    {"city":"Little Rock","state":"Arkansas","abbr":"AR","slug":"little-rock-ar"},
    {"city":"Fort Smith","state":"Arkansas","abbr":"AR","slug":"fort-smith-ar"},
    {"city":"Fayetteville","state":"Arkansas","abbr":"AR","slug":"fayetteville-ar"},
    {"city":"Springdale","state":"Arkansas","abbr":"AR","slug":"springdale-ar"},
    {"city":"Jonesboro","state":"Arkansas","abbr":"AR","slug":"jonesboro-ar"},
    {"city":"North Little Rock","state":"Arkansas","abbr":"AR","slug":"north-little-rock-ar"},
    {"city":"Conway","state":"Arkansas","abbr":"AR","slug":"conway-ar"},
    {"city":"Rogers","state":"Arkansas","abbr":"AR","slug":"rogers-ar"},
    # California
    {"city":"Los Angeles","state":"California","abbr":"CA","slug":"los-angeles-ca"},
    {"city":"San Diego","state":"California","abbr":"CA","slug":"san-diego-ca"},
    {"city":"San Jose","state":"California","abbr":"CA","slug":"san-jose-ca"},
    {"city":"San Francisco","state":"California","abbr":"CA","slug":"san-francisco-ca"},
    {"city":"Fresno","state":"California","abbr":"CA","slug":"fresno-ca"},
    {"city":"Sacramento","state":"California","abbr":"CA","slug":"sacramento-ca"},
    {"city":"Long Beach","state":"California","abbr":"CA","slug":"long-beach-ca"},
    {"city":"Oakland","state":"California","abbr":"CA","slug":"oakland-ca"},
    {"city":"Bakersfield","state":"California","abbr":"CA","slug":"bakersfield-ca"},
    {"city":"Anaheim","state":"California","abbr":"CA","slug":"anaheim-ca"},
    {"city":"Santa Ana","state":"California","abbr":"CA","slug":"santa-ana-ca"},
    {"city":"Riverside","state":"California","abbr":"CA","slug":"riverside-ca"},
    {"city":"Stockton","state":"California","abbr":"CA","slug":"stockton-ca"},
    {"city":"Irvine","state":"California","abbr":"CA","slug":"irvine-ca"},
    {"city":"Chula Vista","state":"California","abbr":"CA","slug":"chula-vista-ca"},
    {"city":"Fremont","state":"California","abbr":"CA","slug":"fremont-ca"},
    {"city":"San Bernardino","state":"California","abbr":"CA","slug":"san-bernardino-ca"},
    {"city":"Modesto","state":"California","abbr":"CA","slug":"modesto-ca"},
    {"city":"Fontana","state":"California","abbr":"CA","slug":"fontana-ca"},
    {"city":"Moreno Valley","state":"California","abbr":"CA","slug":"moreno-valley-ca"},
    {"city":"Glendale","state":"California","abbr":"CA","slug":"glendale-ca"},
    {"city":"Huntington Beach","state":"California","abbr":"CA","slug":"huntington-beach-ca"},
    {"city":"Santa Clarita","state":"California","abbr":"CA","slug":"santa-clarita-ca"},
    {"city":"Garden Grove","state":"California","abbr":"CA","slug":"garden-grove-ca"},
    {"city":"Oceanside","state":"California","abbr":"CA","slug":"oceanside-ca"},
    {"city":"Rancho Cucamonga","state":"California","abbr":"CA","slug":"rancho-cucamonga-ca"},
    {"city":"Santa Rosa","state":"California","abbr":"CA","slug":"santa-rosa-ca"},
    {"city":"Ontario","state":"California","abbr":"CA","slug":"ontario-ca"},
    {"city":"Lancaster","state":"California","abbr":"CA","slug":"lancaster-ca"},
    {"city":"Elk Grove","state":"California","abbr":"CA","slug":"elk-grove-ca"},
    {"city":"Corona","state":"California","abbr":"CA","slug":"corona-ca"},
    {"city":"Palmdale","state":"California","abbr":"CA","slug":"palmdale-ca"},
    {"city":"Salinas","state":"California","abbr":"CA","slug":"salinas-ca"},
    {"city":"Pomona","state":"California","abbr":"CA","slug":"pomona-ca"},
    {"city":"Torrance","state":"California","abbr":"CA","slug":"torrance-ca"},
    {"city":"Escondido","state":"California","abbr":"CA","slug":"escondido-ca"},
    {"city":"Pasadena","state":"California","abbr":"CA","slug":"pasadena-ca"},
    {"city":"Sunnyvale","state":"California","abbr":"CA","slug":"sunnyvale-ca"},
    {"city":"Hayward","state":"California","abbr":"CA","slug":"hayward-ca"},
    {"city":"Palo Alto","state":"California","abbr":"CA","slug":"palo-alto-ca"},
    {"city":"Burbank","state":"California","abbr":"CA","slug":"burbank-ca"},
    {"city":"Santa Barbara","state":"California","abbr":"CA","slug":"santa-barbara-ca"},
    {"city":"Oxnard","state":"California","abbr":"CA","slug":"oxnard-ca"},
    {"city":"Visalia","state":"California","abbr":"CA","slug":"visalia-ca"},
    {"city":"Berkeley","state":"California","abbr":"CA","slug":"berkeley-ca"},
    # Colorado
    {"city":"Denver","state":"Colorado","abbr":"CO","slug":"denver-co"},
    {"city":"Colorado Springs","state":"Colorado","abbr":"CO","slug":"colorado-springs-co"},
    {"city":"Aurora","state":"Colorado","abbr":"CO","slug":"aurora-co"},
    {"city":"Fort Collins","state":"Colorado","abbr":"CO","slug":"fort-collins-co"},
    {"city":"Lakewood","state":"Colorado","abbr":"CO","slug":"lakewood-co"},
    {"city":"Thornton","state":"Colorado","abbr":"CO","slug":"thornton-co"},
    {"city":"Arvada","state":"Colorado","abbr":"CO","slug":"arvada-co"},
    {"city":"Westminster","state":"Colorado","abbr":"CO","slug":"westminster-co"},
    {"city":"Pueblo","state":"Colorado","abbr":"CO","slug":"pueblo-co"},
    {"city":"Boulder","state":"Colorado","abbr":"CO","slug":"boulder-co"},
    {"city":"Greeley","state":"Colorado","abbr":"CO","slug":"greeley-co"},
    {"city":"Longmont","state":"Colorado","abbr":"CO","slug":"longmont-co"},
    # Connecticut
    {"city":"Bridgeport","state":"Connecticut","abbr":"CT","slug":"bridgeport-ct"},
    {"city":"New Haven","state":"Connecticut","abbr":"CT","slug":"new-haven-ct"},
    {"city":"Stamford","state":"Connecticut","abbr":"CT","slug":"stamford-ct"},
    {"city":"Hartford","state":"Connecticut","abbr":"CT","slug":"hartford-ct"},
    {"city":"Waterbury","state":"Connecticut","abbr":"CT","slug":"waterbury-ct"},
    {"city":"Norwalk","state":"Connecticut","abbr":"CT","slug":"norwalk-ct"},
    {"city":"Danbury","state":"Connecticut","abbr":"CT","slug":"danbury-ct"},
    {"city":"New Britain","state":"Connecticut","abbr":"CT","slug":"new-britain-ct"},
    # Delaware
    {"city":"Wilmington","state":"Delaware","abbr":"DE","slug":"wilmington-de"},
    {"city":"Dover","state":"Delaware","abbr":"DE","slug":"dover-de"},
    {"city":"Newark","state":"Delaware","abbr":"DE","slug":"newark-de"},
    # Florida
    {"city":"Jacksonville","state":"Florida","abbr":"FL","slug":"jacksonville-fl"},
    {"city":"Miami","state":"Florida","abbr":"FL","slug":"miami-fl"},
    {"city":"Tampa","state":"Florida","abbr":"FL","slug":"tampa-fl"},
    {"city":"Orlando","state":"Florida","abbr":"FL","slug":"orlando-fl"},
    {"city":"St. Petersburg","state":"Florida","abbr":"FL","slug":"st-petersburg-fl"},
    {"city":"Hialeah","state":"Florida","abbr":"FL","slug":"hialeah-fl"},
    {"city":"Port St. Lucie","state":"Florida","abbr":"FL","slug":"port-st-lucie-fl"},
    {"city":"Cape Coral","state":"Florida","abbr":"FL","slug":"cape-coral-fl"},
    {"city":"Tallahassee","state":"Florida","abbr":"FL","slug":"tallahassee-fl"},
    {"city":"Fort Lauderdale","state":"Florida","abbr":"FL","slug":"fort-lauderdale-fl"},
    {"city":"Pembroke Pines","state":"Florida","abbr":"FL","slug":"pembroke-pines-fl"},
    {"city":"Hollywood","state":"Florida","abbr":"FL","slug":"hollywood-fl"},
    {"city":"Gainesville","state":"Florida","abbr":"FL","slug":"gainesville-fl"},
    {"city":"Miramar","state":"Florida","abbr":"FL","slug":"miramar-fl"},
    {"city":"Coral Springs","state":"Florida","abbr":"FL","slug":"coral-springs-fl"},
    {"city":"Clearwater","state":"Florida","abbr":"FL","slug":"clearwater-fl"},
    {"city":"Palm Bay","state":"Florida","abbr":"FL","slug":"palm-bay-fl"},
    {"city":"Pompano Beach","state":"Florida","abbr":"FL","slug":"pompano-beach-fl"},
    {"city":"West Palm Beach","state":"Florida","abbr":"FL","slug":"west-palm-beach-fl"},
    {"city":"Lakeland","state":"Florida","abbr":"FL","slug":"lakeland-fl"},
    {"city":"Davie","state":"Florida","abbr":"FL","slug":"davie-fl"},
    {"city":"Miami Gardens","state":"Florida","abbr":"FL","slug":"miami-gardens-fl"},
    {"city":"Boca Raton","state":"Florida","abbr":"FL","slug":"boca-raton-fl"},
    {"city":"Sunrise","state":"Florida","abbr":"FL","slug":"sunrise-fl"},
    {"city":"Deltona","state":"Florida","abbr":"FL","slug":"deltona-fl"},
    {"city":"Fort Myers","state":"Florida","abbr":"FL","slug":"fort-myers-fl"},
    {"city":"Daytona Beach","state":"Florida","abbr":"FL","slug":"daytona-beach-fl"},
    {"city":"Sarasota","state":"Florida","abbr":"FL","slug":"sarasota-fl"},
    {"city":"Ocala","state":"Florida","abbr":"FL","slug":"ocala-fl"},
    # Georgia
    {"city":"Atlanta","state":"Georgia","abbr":"GA","slug":"atlanta-ga"},
    {"city":"Columbus","state":"Georgia","abbr":"GA","slug":"columbus-ga"},
    {"city":"Augusta","state":"Georgia","abbr":"GA","slug":"augusta-ga"},
    {"city":"Savannah","state":"Georgia","abbr":"GA","slug":"savannah-ga"},
    {"city":"Athens","state":"Georgia","abbr":"GA","slug":"athens-ga"},
    {"city":"Sandy Springs","state":"Georgia","abbr":"GA","slug":"sandy-springs-ga"},
    {"city":"Roswell","state":"Georgia","abbr":"GA","slug":"roswell-ga"},
    {"city":"Macon","state":"Georgia","abbr":"GA","slug":"macon-ga"},
    {"city":"Johns Creek","state":"Georgia","abbr":"GA","slug":"johns-creek-ga"},
    {"city":"Albany","state":"Georgia","abbr":"GA","slug":"albany-ga"},
    {"city":"Warner Robins","state":"Georgia","abbr":"GA","slug":"warner-robins-ga"},
    {"city":"Alpharetta","state":"Georgia","abbr":"GA","slug":"alpharetta-ga"},
    {"city":"Marietta","state":"Georgia","abbr":"GA","slug":"marietta-ga"},
    # Hawaii
    {"city":"Honolulu","state":"Hawaii","abbr":"HI","slug":"honolulu-hi"},
    {"city":"Pearl City","state":"Hawaii","abbr":"HI","slug":"pearl-city-hi"},
    {"city":"Hilo","state":"Hawaii","abbr":"HI","slug":"hilo-hi"},
    {"city":"Kailua","state":"Hawaii","abbr":"HI","slug":"kailua-hi"},
    # Idaho
    {"city":"Boise","state":"Idaho","abbr":"ID","slug":"boise-id"},
    {"city":"Nampa","state":"Idaho","abbr":"ID","slug":"nampa-id"},
    {"city":"Meridian","state":"Idaho","abbr":"ID","slug":"meridian-id"},
    {"city":"Idaho Falls","state":"Idaho","abbr":"ID","slug":"idaho-falls-id"},
    {"city":"Pocatello","state":"Idaho","abbr":"ID","slug":"pocatello-id"},
    {"city":"Caldwell","state":"Idaho","abbr":"ID","slug":"caldwell-id"},
    # Illinois
    {"city":"Chicago","state":"Illinois","abbr":"IL","slug":"chicago-il"},
    {"city":"Aurora","state":"Illinois","abbr":"IL","slug":"aurora-il"},
    {"city":"Joliet","state":"Illinois","abbr":"IL","slug":"joliet-il"},
    {"city":"Naperville","state":"Illinois","abbr":"IL","slug":"naperville-il"},
    {"city":"Rockford","state":"Illinois","abbr":"IL","slug":"rockford-il"},
    {"city":"Springfield","state":"Illinois","abbr":"IL","slug":"springfield-il"},
    {"city":"Elgin","state":"Illinois","abbr":"IL","slug":"elgin-il"},
    {"city":"Peoria","state":"Illinois","abbr":"IL","slug":"peoria-il"},
    {"city":"Champaign","state":"Illinois","abbr":"IL","slug":"champaign-il"},
    {"city":"Waukegan","state":"Illinois","abbr":"IL","slug":"waukegan-il"},
    {"city":"Bloomington","state":"Illinois","abbr":"IL","slug":"bloomington-il"},
    {"city":"Evanston","state":"Illinois","abbr":"IL","slug":"evanston-il"},
    {"city":"Schaumburg","state":"Illinois","abbr":"IL","slug":"schaumburg-il"},
    # Indiana
    {"city":"Indianapolis","state":"Indiana","abbr":"IN","slug":"indianapolis-in"},
    {"city":"Fort Wayne","state":"Indiana","abbr":"IN","slug":"fort-wayne-in"},
    {"city":"Evansville","state":"Indiana","abbr":"IN","slug":"evansville-in"},
    {"city":"South Bend","state":"Indiana","abbr":"IN","slug":"south-bend-in"},
    {"city":"Carmel","state":"Indiana","abbr":"IN","slug":"carmel-in"},
    {"city":"Fishers","state":"Indiana","abbr":"IN","slug":"fishers-in"},
    {"city":"Bloomington","state":"Indiana","abbr":"IN","slug":"bloomington-in"},
    {"city":"Hammond","state":"Indiana","abbr":"IN","slug":"hammond-in"},
    {"city":"Gary","state":"Indiana","abbr":"IN","slug":"gary-in"},
    {"city":"Muncie","state":"Indiana","abbr":"IN","slug":"muncie-in"},
    {"city":"Lafayette","state":"Indiana","abbr":"IN","slug":"lafayette-in"},
    # Iowa
    {"city":"Des Moines","state":"Iowa","abbr":"IA","slug":"des-moines-ia"},
    {"city":"Cedar Rapids","state":"Iowa","abbr":"IA","slug":"cedar-rapids-ia"},
    {"city":"Davenport","state":"Iowa","abbr":"IA","slug":"davenport-ia"},
    {"city":"Sioux City","state":"Iowa","abbr":"IA","slug":"sioux-city-ia"},
    {"city":"Iowa City","state":"Iowa","abbr":"IA","slug":"iowa-city-ia"},
    {"city":"Waterloo","state":"Iowa","abbr":"IA","slug":"waterloo-ia"},
    {"city":"Ames","state":"Iowa","abbr":"IA","slug":"ames-ia"},
    # Kansas
    {"city":"Wichita","state":"Kansas","abbr":"KS","slug":"wichita-ks"},
    {"city":"Overland Park","state":"Kansas","abbr":"KS","slug":"overland-park-ks"},
    {"city":"Kansas City","state":"Kansas","abbr":"KS","slug":"kansas-city-ks"},
    {"city":"Topeka","state":"Kansas","abbr":"KS","slug":"topeka-ks"},
    {"city":"Olathe","state":"Kansas","abbr":"KS","slug":"olathe-ks"},
    {"city":"Lawrence","state":"Kansas","abbr":"KS","slug":"lawrence-ks"},
    {"city":"Shawnee","state":"Kansas","abbr":"KS","slug":"shawnee-ks"},
    # Kentucky
    {"city":"Louisville","state":"Kentucky","abbr":"KY","slug":"louisville-ky"},
    {"city":"Lexington","state":"Kentucky","abbr":"KY","slug":"lexington-ky"},
    {"city":"Bowling Green","state":"Kentucky","abbr":"KY","slug":"bowling-green-ky"},
    {"city":"Owensboro","state":"Kentucky","abbr":"KY","slug":"owensboro-ky"},
    {"city":"Covington","state":"Kentucky","abbr":"KY","slug":"covington-ky"},
    {"city":"Richmond","state":"Kentucky","abbr":"KY","slug":"richmond-ky"},
    {"city":"Georgetown","state":"Kentucky","abbr":"KY","slug":"georgetown-ky"},
    # Louisiana
    {"city":"New Orleans","state":"Louisiana","abbr":"LA","slug":"new-orleans-la"},
    {"city":"Baton Rouge","state":"Louisiana","abbr":"LA","slug":"baton-rouge-la"},
    {"city":"Shreveport","state":"Louisiana","abbr":"LA","slug":"shreveport-la"},
    {"city":"Metairie","state":"Louisiana","abbr":"LA","slug":"metairie-la"},
    {"city":"Lafayette","state":"Louisiana","abbr":"LA","slug":"lafayette-la"},
    {"city":"Lake Charles","state":"Louisiana","abbr":"LA","slug":"lake-charles-la"},
    {"city":"Monroe","state":"Louisiana","abbr":"LA","slug":"monroe-la"},
    {"city":"Alexandria","state":"Louisiana","abbr":"LA","slug":"alexandria-la"},
    # Maine
    {"city":"Portland","state":"Maine","abbr":"ME","slug":"portland-me"},
    {"city":"Lewiston","state":"Maine","abbr":"ME","slug":"lewiston-me"},
    {"city":"Bangor","state":"Maine","abbr":"ME","slug":"bangor-me"},
    {"city":"South Portland","state":"Maine","abbr":"ME","slug":"south-portland-me"},
    # Maryland
    {"city":"Baltimore","state":"Maryland","abbr":"MD","slug":"baltimore-md"},
    {"city":"Columbia","state":"Maryland","abbr":"MD","slug":"columbia-md"},
    {"city":"Germantown","state":"Maryland","abbr":"MD","slug":"germantown-md"},
    {"city":"Silver Spring","state":"Maryland","abbr":"MD","slug":"silver-spring-md"},
    {"city":"Waldorf","state":"Maryland","abbr":"MD","slug":"waldorf-md"},
    {"city":"Frederick","state":"Maryland","abbr":"MD","slug":"frederick-md"},
    {"city":"Ellicott City","state":"Maryland","abbr":"MD","slug":"ellicott-city-md"},
    {"city":"Gaithersburg","state":"Maryland","abbr":"MD","slug":"gaithersburg-md"},
    {"city":"Rockville","state":"Maryland","abbr":"MD","slug":"rockville-md"},
    {"city":"Bethesda","state":"Maryland","abbr":"MD","slug":"bethesda-md"},
    {"city":"Annapolis","state":"Maryland","abbr":"MD","slug":"annapolis-md"},
    # Massachusetts
    {"city":"Boston","state":"Massachusetts","abbr":"MA","slug":"boston-ma"},
    {"city":"Worcester","state":"Massachusetts","abbr":"MA","slug":"worcester-ma"},
    {"city":"Springfield","state":"Massachusetts","abbr":"MA","slug":"springfield-ma"},
    {"city":"Lowell","state":"Massachusetts","abbr":"MA","slug":"lowell-ma"},
    {"city":"Cambridge","state":"Massachusetts","abbr":"MA","slug":"cambridge-ma"},
    {"city":"New Bedford","state":"Massachusetts","abbr":"MA","slug":"new-bedford-ma"},
    {"city":"Brockton","state":"Massachusetts","abbr":"MA","slug":"brockton-ma"},
    {"city":"Quincy","state":"Massachusetts","abbr":"MA","slug":"quincy-ma"},
    {"city":"Lynn","state":"Massachusetts","abbr":"MA","slug":"lynn-ma"},
    {"city":"Fall River","state":"Massachusetts","abbr":"MA","slug":"fall-river-ma"},
    {"city":"Newton","state":"Massachusetts","abbr":"MA","slug":"newton-ma"},
    {"city":"Somerville","state":"Massachusetts","abbr":"MA","slug":"somerville-ma"},
    # Michigan
    {"city":"Detroit","state":"Michigan","abbr":"MI","slug":"detroit-mi"},
    {"city":"Grand Rapids","state":"Michigan","abbr":"MI","slug":"grand-rapids-mi"},
    {"city":"Warren","state":"Michigan","abbr":"MI","slug":"warren-mi"},
    {"city":"Sterling Heights","state":"Michigan","abbr":"MI","slug":"sterling-heights-mi"},
    {"city":"Ann Arbor","state":"Michigan","abbr":"MI","slug":"ann-arbor-mi"},
    {"city":"Lansing","state":"Michigan","abbr":"MI","slug":"lansing-mi"},
    {"city":"Flint","state":"Michigan","abbr":"MI","slug":"flint-mi"},
    {"city":"Dearborn","state":"Michigan","abbr":"MI","slug":"dearborn-mi"},
    {"city":"Livonia","state":"Michigan","abbr":"MI","slug":"livonia-mi"},
    {"city":"Westland","state":"Michigan","abbr":"MI","slug":"westland-mi"},
    {"city":"Troy","state":"Michigan","abbr":"MI","slug":"troy-mi"},
    {"city":"Farmington Hills","state":"Michigan","abbr":"MI","slug":"farmington-hills-mi"},
    {"city":"Kalamazoo","state":"Michigan","abbr":"MI","slug":"kalamazoo-mi"},
    {"city":"Wyoming","state":"Michigan","abbr":"MI","slug":"wyoming-mi"},
    {"city":"Southfield","state":"Michigan","abbr":"MI","slug":"southfield-mi"},
    # Minnesota
    {"city":"Minneapolis","state":"Minnesota","abbr":"MN","slug":"minneapolis-mn"},
    {"city":"Saint Paul","state":"Minnesota","abbr":"MN","slug":"saint-paul-mn"},
    {"city":"Rochester","state":"Minnesota","abbr":"MN","slug":"rochester-mn"},
    {"city":"Duluth","state":"Minnesota","abbr":"MN","slug":"duluth-mn"},
    {"city":"Brooklyn Park","state":"Minnesota","abbr":"MN","slug":"brooklyn-park-mn"},
    {"city":"Plymouth","state":"Minnesota","abbr":"MN","slug":"plymouth-mn"},
    {"city":"Maple Grove","state":"Minnesota","abbr":"MN","slug":"maple-grove-mn"},
    {"city":"Woodbury","state":"Minnesota","abbr":"MN","slug":"woodbury-mn"},
    {"city":"Blaine","state":"Minnesota","abbr":"MN","slug":"blaine-mn"},
    {"city":"Eden Prairie","state":"Minnesota","abbr":"MN","slug":"eden-prairie-mn"},
    # Mississippi
    {"city":"Jackson","state":"Mississippi","abbr":"MS","slug":"jackson-ms"},
    {"city":"Gulfport","state":"Mississippi","abbr":"MS","slug":"gulfport-ms"},
    {"city":"Southaven","state":"Mississippi","abbr":"MS","slug":"southaven-ms"},
    {"city":"Hattiesburg","state":"Mississippi","abbr":"MS","slug":"hattiesburg-ms"},
    {"city":"Biloxi","state":"Mississippi","abbr":"MS","slug":"biloxi-ms"},
    {"city":"Meridian","state":"Mississippi","abbr":"MS","slug":"meridian-ms"},
    # Missouri
    {"city":"Kansas City","state":"Missouri","abbr":"MO","slug":"kansas-city-mo"},
    {"city":"St. Louis","state":"Missouri","abbr":"MO","slug":"st-louis-mo"},
    {"city":"Springfield","state":"Missouri","abbr":"MO","slug":"springfield-mo"},
    {"city":"Columbia","state":"Missouri","abbr":"MO","slug":"columbia-mo"},
    {"city":"Independence","state":"Missouri","abbr":"MO","slug":"independence-mo"},
    {"city":"Lee's Summit","state":"Missouri","abbr":"MO","slug":"lees-summit-mo"},
    {"city":"O'Fallon","state":"Missouri","abbr":"MO","slug":"ofallon-mo"},
    {"city":"St. Joseph","state":"Missouri","abbr":"MO","slug":"st-joseph-mo"},
    {"city":"St. Charles","state":"Missouri","abbr":"MO","slug":"st-charles-mo"},
    {"city":"Blue Springs","state":"Missouri","abbr":"MO","slug":"blue-springs-mo"},
    # Montana
    {"city":"Billings","state":"Montana","abbr":"MT","slug":"billings-mt"},
    {"city":"Missoula","state":"Montana","abbr":"MT","slug":"missoula-mt"},
    {"city":"Great Falls","state":"Montana","abbr":"MT","slug":"great-falls-mt"},
    {"city":"Bozeman","state":"Montana","abbr":"MT","slug":"bozeman-mt"},
    {"city":"Butte","state":"Montana","abbr":"MT","slug":"butte-mt"},
    # Nebraska
    {"city":"Omaha","state":"Nebraska","abbr":"NE","slug":"omaha-ne"},
    {"city":"Lincoln","state":"Nebraska","abbr":"NE","slug":"lincoln-ne"},
    {"city":"Bellevue","state":"Nebraska","abbr":"NE","slug":"bellevue-ne"},
    {"city":"Grand Island","state":"Nebraska","abbr":"NE","slug":"grand-island-ne"},
    {"city":"Kearney","state":"Nebraska","abbr":"NE","slug":"kearney-ne"},
    # Nevada
    {"city":"Las Vegas","state":"Nevada","abbr":"NV","slug":"las-vegas-nv"},
    {"city":"Henderson","state":"Nevada","abbr":"NV","slug":"henderson-nv"},
    {"city":"Reno","state":"Nevada","abbr":"NV","slug":"reno-nv"},
    {"city":"North Las Vegas","state":"Nevada","abbr":"NV","slug":"north-las-vegas-nv"},
    {"city":"Sparks","state":"Nevada","abbr":"NV","slug":"sparks-nv"},
    {"city":"Carson City","state":"Nevada","abbr":"NV","slug":"carson-city-nv"},
    # New Hampshire
    {"city":"Manchester","state":"New Hampshire","abbr":"NH","slug":"manchester-nh"},
    {"city":"Nashua","state":"New Hampshire","abbr":"NH","slug":"nashua-nh"},
    {"city":"Concord","state":"New Hampshire","abbr":"NH","slug":"concord-nh"},
    {"city":"Derry","state":"New Hampshire","abbr":"NH","slug":"derry-nh"},
    {"city":"Dover","state":"New Hampshire","abbr":"NH","slug":"dover-nh"},
    # New Jersey
    {"city":"Newark","state":"New Jersey","abbr":"NJ","slug":"newark-nj"},
    {"city":"Jersey City","state":"New Jersey","abbr":"NJ","slug":"jersey-city-nj"},
    {"city":"Paterson","state":"New Jersey","abbr":"NJ","slug":"paterson-nj"},
    {"city":"Elizabeth","state":"New Jersey","abbr":"NJ","slug":"elizabeth-nj"},
    {"city":"Edison","state":"New Jersey","abbr":"NJ","slug":"edison-nj"},
    {"city":"Woodbridge","state":"New Jersey","abbr":"NJ","slug":"woodbridge-nj"},
    {"city":"Lakewood","state":"New Jersey","abbr":"NJ","slug":"lakewood-nj"},
    {"city":"Toms River","state":"New Jersey","abbr":"NJ","slug":"toms-river-nj"},
    {"city":"Hamilton","state":"New Jersey","abbr":"NJ","slug":"hamilton-nj"},
    {"city":"Trenton","state":"New Jersey","abbr":"NJ","slug":"trenton-nj"},
    {"city":"Clifton","state":"New Jersey","abbr":"NJ","slug":"clifton-nj"},
    {"city":"Camden","state":"New Jersey","abbr":"NJ","slug":"camden-nj"},
    {"city":"Brick","state":"New Jersey","abbr":"NJ","slug":"brick-nj"},
    {"city":"Cherry Hill","state":"New Jersey","abbr":"NJ","slug":"cherry-hill-nj"},
    {"city":"Passaic","state":"New Jersey","abbr":"NJ","slug":"passaic-nj"},
    # New Mexico
    {"city":"Albuquerque","state":"New Mexico","abbr":"NM","slug":"albuquerque-nm"},
    {"city":"Las Cruces","state":"New Mexico","abbr":"NM","slug":"las-cruces-nm"},
    {"city":"Rio Rancho","state":"New Mexico","abbr":"NM","slug":"rio-rancho-nm"},
    {"city":"Santa Fe","state":"New Mexico","abbr":"NM","slug":"santa-fe-nm"},
    {"city":"Roswell","state":"New Mexico","abbr":"NM","slug":"roswell-nm"},
    # New York
    {"city":"New York City","state":"New York","abbr":"NY","slug":"new-york-city-ny"},
    {"city":"Buffalo","state":"New York","abbr":"NY","slug":"buffalo-ny"},
    {"city":"Rochester","state":"New York","abbr":"NY","slug":"rochester-ny"},
    {"city":"Yonkers","state":"New York","abbr":"NY","slug":"yonkers-ny"},
    {"city":"Syracuse","state":"New York","abbr":"NY","slug":"syracuse-ny"},
    {"city":"Albany","state":"New York","abbr":"NY","slug":"albany-ny"},
    {"city":"New Rochelle","state":"New York","abbr":"NY","slug":"new-rochelle-ny"},
    {"city":"Mount Vernon","state":"New York","abbr":"NY","slug":"mount-vernon-ny"},
    {"city":"Schenectady","state":"New York","abbr":"NY","slug":"schenectady-ny"},
    {"city":"Utica","state":"New York","abbr":"NY","slug":"utica-ny"},
    {"city":"White Plains","state":"New York","abbr":"NY","slug":"white-plains-ny"},
    {"city":"Hempstead","state":"New York","abbr":"NY","slug":"hempstead-ny"},
    {"city":"Troy","state":"New York","abbr":"NY","slug":"troy-ny"},
    {"city":"Niagara Falls","state":"New York","abbr":"NY","slug":"niagara-falls-ny"},
    {"city":"Binghamton","state":"New York","abbr":"NY","slug":"binghamton-ny"},
    {"city":"Freeport","state":"New York","abbr":"NY","slug":"freeport-ny"},
    {"city":"Valley Stream","state":"New York","abbr":"NY","slug":"valley-stream-ny"},
    {"city":"Long Island City","state":"New York","abbr":"NY","slug":"long-island-city-ny"},
    {"city":"Bronx","state":"New York","abbr":"NY","slug":"bronx-ny"},
    {"city":"Brooklyn","state":"New York","abbr":"NY","slug":"brooklyn-ny"},
    {"city":"Queens","state":"New York","abbr":"NY","slug":"queens-ny"},
    {"city":"Staten Island","state":"New York","abbr":"NY","slug":"staten-island-ny"},
    # North Carolina
    {"city":"Charlotte","state":"North Carolina","abbr":"NC","slug":"charlotte-nc"},
    {"city":"Raleigh","state":"North Carolina","abbr":"NC","slug":"raleigh-nc"},
    {"city":"Greensboro","state":"North Carolina","abbr":"NC","slug":"greensboro-nc"},
    {"city":"Durham","state":"North Carolina","abbr":"NC","slug":"durham-nc"},
    {"city":"Winston-Salem","state":"North Carolina","abbr":"NC","slug":"winston-salem-nc"},
    {"city":"Fayetteville","state":"North Carolina","abbr":"NC","slug":"fayetteville-nc"},
    {"city":"Cary","state":"North Carolina","abbr":"NC","slug":"cary-nc"},
    {"city":"Wilmington","state":"North Carolina","abbr":"NC","slug":"wilmington-nc"},
    {"city":"High Point","state":"North Carolina","abbr":"NC","slug":"high-point-nc"},
    {"city":"Concord","state":"North Carolina","abbr":"NC","slug":"concord-nc"},
    {"city":"Asheville","state":"North Carolina","abbr":"NC","slug":"asheville-nc"},
    {"city":"Gastonia","state":"North Carolina","abbr":"NC","slug":"gastonia-nc"},
    {"city":"Jacksonville","state":"North Carolina","abbr":"NC","slug":"jacksonville-nc"},
    # North Dakota
    {"city":"Fargo","state":"North Dakota","abbr":"ND","slug":"fargo-nd"},
    {"city":"Bismarck","state":"North Dakota","abbr":"ND","slug":"bismarck-nd"},
    {"city":"Grand Forks","state":"North Dakota","abbr":"ND","slug":"grand-forks-nd"},
    {"city":"Minot","state":"North Dakota","abbr":"ND","slug":"minot-nd"},
    # Ohio
    {"city":"Columbus","state":"Ohio","abbr":"OH","slug":"columbus-oh"},
    {"city":"Cleveland","state":"Ohio","abbr":"OH","slug":"cleveland-oh"},
    {"city":"Cincinnati","state":"Ohio","abbr":"OH","slug":"cincinnati-oh"},
    {"city":"Toledo","state":"Ohio","abbr":"OH","slug":"toledo-oh"},
    {"city":"Akron","state":"Ohio","abbr":"OH","slug":"akron-oh"},
    {"city":"Dayton","state":"Ohio","abbr":"OH","slug":"dayton-oh"},
    {"city":"Parma","state":"Ohio","abbr":"OH","slug":"parma-oh"},
    {"city":"Canton","state":"Ohio","abbr":"OH","slug":"canton-oh"},
    {"city":"Youngstown","state":"Ohio","abbr":"OH","slug":"youngstown-oh"},
    {"city":"Lorain","state":"Ohio","abbr":"OH","slug":"lorain-oh"},
    {"city":"Hamilton","state":"Ohio","abbr":"OH","slug":"hamilton-oh"},
    {"city":"Springfield","state":"Ohio","abbr":"OH","slug":"springfield-oh"},
    {"city":"Kettering","state":"Ohio","abbr":"OH","slug":"kettering-oh"},
    {"city":"Elyria","state":"Ohio","abbr":"OH","slug":"elyria-oh"},
    # Oklahoma
    {"city":"Oklahoma City","state":"Oklahoma","abbr":"OK","slug":"oklahoma-city-ok"},
    {"city":"Tulsa","state":"Oklahoma","abbr":"OK","slug":"tulsa-ok"},
    {"city":"Norman","state":"Oklahoma","abbr":"OK","slug":"norman-ok"},
    {"city":"Broken Arrow","state":"Oklahoma","abbr":"OK","slug":"broken-arrow-ok"},
    {"city":"Lawton","state":"Oklahoma","abbr":"OK","slug":"lawton-ok"},
    {"city":"Edmond","state":"Oklahoma","abbr":"OK","slug":"edmond-ok"},
    {"city":"Moore","state":"Oklahoma","abbr":"OK","slug":"moore-ok"},
    {"city":"Midwest City","state":"Oklahoma","abbr":"OK","slug":"midwest-city-ok"},
    # Oregon
    {"city":"Portland","state":"Oregon","abbr":"OR","slug":"portland-or"},
    {"city":"Salem","state":"Oregon","abbr":"OR","slug":"salem-or"},
    {"city":"Eugene","state":"Oregon","abbr":"OR","slug":"eugene-or"},
    {"city":"Gresham","state":"Oregon","abbr":"OR","slug":"gresham-or"},
    {"city":"Hillsboro","state":"Oregon","abbr":"OR","slug":"hillsboro-or"},
    {"city":"Beaverton","state":"Oregon","abbr":"OR","slug":"beaverton-or"},
    {"city":"Bend","state":"Oregon","abbr":"OR","slug":"bend-or"},
    {"city":"Medford","state":"Oregon","abbr":"OR","slug":"medford-or"},
    {"city":"Springfield","state":"Oregon","abbr":"OR","slug":"springfield-or"},
    {"city":"Corvallis","state":"Oregon","abbr":"OR","slug":"corvallis-or"},
    # Pennsylvania
    {"city":"Philadelphia","state":"Pennsylvania","abbr":"PA","slug":"philadelphia-pa"},
    {"city":"Pittsburgh","state":"Pennsylvania","abbr":"PA","slug":"pittsburgh-pa"},
    {"city":"Allentown","state":"Pennsylvania","abbr":"PA","slug":"allentown-pa"},
    {"city":"Erie","state":"Pennsylvania","abbr":"PA","slug":"erie-pa"},
    {"city":"Reading","state":"Pennsylvania","abbr":"PA","slug":"reading-pa"},
    {"city":"Scranton","state":"Pennsylvania","abbr":"PA","slug":"scranton-pa"},
    {"city":"Bethlehem","state":"Pennsylvania","abbr":"PA","slug":"bethlehem-pa"},
    {"city":"Lancaster","state":"Pennsylvania","abbr":"PA","slug":"lancaster-pa"},
    {"city":"Harrisburg","state":"Pennsylvania","abbr":"PA","slug":"harrisburg-pa"},
    {"city":"Altoona","state":"Pennsylvania","abbr":"PA","slug":"altoona-pa"},
    {"city":"York","state":"Pennsylvania","abbr":"PA","slug":"york-pa"},
    {"city":"Wilkes-Barre","state":"Pennsylvania","abbr":"PA","slug":"wilkes-barre-pa"},
    {"city":"Chester","state":"Pennsylvania","abbr":"PA","slug":"chester-pa"},
    # Rhode Island
    {"city":"Providence","state":"Rhode Island","abbr":"RI","slug":"providence-ri"},
    {"city":"Cranston","state":"Rhode Island","abbr":"RI","slug":"cranston-ri"},
    {"city":"Warwick","state":"Rhode Island","abbr":"RI","slug":"warwick-ri"},
    {"city":"Pawtucket","state":"Rhode Island","abbr":"RI","slug":"pawtucket-ri"},
    # South Carolina
    {"city":"Columbia","state":"South Carolina","abbr":"SC","slug":"columbia-sc"},
    {"city":"Charleston","state":"South Carolina","abbr":"SC","slug":"charleston-sc"},
    {"city":"North Charleston","state":"South Carolina","abbr":"SC","slug":"north-charleston-sc"},
    {"city":"Mount Pleasant","state":"South Carolina","abbr":"SC","slug":"mount-pleasant-sc"},
    {"city":"Rock Hill","state":"South Carolina","abbr":"SC","slug":"rock-hill-sc"},
    {"city":"Greenville","state":"South Carolina","abbr":"SC","slug":"greenville-sc"},
    {"city":"Summerville","state":"South Carolina","abbr":"SC","slug":"summerville-sc"},
    {"city":"Goose Creek","state":"South Carolina","abbr":"SC","slug":"goose-creek-sc"},
    # South Dakota
    {"city":"Sioux Falls","state":"South Dakota","abbr":"SD","slug":"sioux-falls-sd"},
    {"city":"Rapid City","state":"South Dakota","abbr":"SD","slug":"rapid-city-sd"},
    {"city":"Aberdeen","state":"South Dakota","abbr":"SD","slug":"aberdeen-sd"},
    # Tennessee
    {"city":"Memphis","state":"Tennessee","abbr":"TN","slug":"memphis-tn"},
    {"city":"Nashville","state":"Tennessee","abbr":"TN","slug":"nashville-tn"},
    {"city":"Knoxville","state":"Tennessee","abbr":"TN","slug":"knoxville-tn"},
    {"city":"Chattanooga","state":"Tennessee","abbr":"TN","slug":"chattanooga-tn"},
    {"city":"Clarksville","state":"Tennessee","abbr":"TN","slug":"clarksville-tn"},
    {"city":"Murfreesboro","state":"Tennessee","abbr":"TN","slug":"murfreesboro-tn"},
    {"city":"Franklin","state":"Tennessee","abbr":"TN","slug":"franklin-tn"},
    {"city":"Jackson","state":"Tennessee","abbr":"TN","slug":"jackson-tn"},
    {"city":"Johnson City","state":"Tennessee","abbr":"TN","slug":"johnson-city-tn"},
    {"city":"Bartlett","state":"Tennessee","abbr":"TN","slug":"bartlett-tn"},
    {"city":"Hendersonville","state":"Tennessee","abbr":"TN","slug":"hendersonville-tn"},
    {"city":"Kingsport","state":"Tennessee","abbr":"TN","slug":"kingsport-tn"},
    # Texas
    {"city":"Houston","state":"Texas","abbr":"TX","slug":"houston-tx"},
    {"city":"San Antonio","state":"Texas","abbr":"TX","slug":"san-antonio-tx"},
    {"city":"Dallas","state":"Texas","abbr":"TX","slug":"dallas-tx"},
    {"city":"Austin","state":"Texas","abbr":"TX","slug":"austin-tx"},
    {"city":"Fort Worth","state":"Texas","abbr":"TX","slug":"fort-worth-tx"},
    {"city":"El Paso","state":"Texas","abbr":"TX","slug":"el-paso-tx"},
    {"city":"Arlington","state":"Texas","abbr":"TX","slug":"arlington-tx"},
    {"city":"Corpus Christi","state":"Texas","abbr":"TX","slug":"corpus-christi-tx"},
    {"city":"Plano","state":"Texas","abbr":"TX","slug":"plano-tx"},
    {"city":"Laredo","state":"Texas","abbr":"TX","slug":"laredo-tx"},
    {"city":"Lubbock","state":"Texas","abbr":"TX","slug":"lubbock-tx"},
    {"city":"Garland","state":"Texas","abbr":"TX","slug":"garland-tx"},
    {"city":"Irving","state":"Texas","abbr":"TX","slug":"irving-tx"},
    {"city":"Amarillo","state":"Texas","abbr":"TX","slug":"amarillo-tx"},
    {"city":"Grand Prairie","state":"Texas","abbr":"TX","slug":"grand-prairie-tx"},
    {"city":"McKinney","state":"Texas","abbr":"TX","slug":"mckinney-tx"},
    {"city":"Frisco","state":"Texas","abbr":"TX","slug":"frisco-tx"},
    {"city":"Brownsville","state":"Texas","abbr":"TX","slug":"brownsville-tx"},
    {"city":"Pasadena","state":"Texas","abbr":"TX","slug":"pasadena-tx"},
    {"city":"Killeen","state":"Texas","abbr":"TX","slug":"killeen-tx"},
    {"city":"McAllen","state":"Texas","abbr":"TX","slug":"mcallen-tx"},
    {"city":"Mesquite","state":"Texas","abbr":"TX","slug":"mesquite-tx"},
    {"city":"Midland","state":"Texas","abbr":"TX","slug":"midland-tx"},
    {"city":"Denton","state":"Texas","abbr":"TX","slug":"denton-tx"},
    {"city":"Waco","state":"Texas","abbr":"TX","slug":"waco-tx"},
    {"city":"Carrollton","state":"Texas","abbr":"TX","slug":"carrollton-tx"},
    {"city":"Round Rock","state":"Texas","abbr":"TX","slug":"round-rock-tx"},
    {"city":"Abilene","state":"Texas","abbr":"TX","slug":"abilene-tx"},
    {"city":"Beaumont","state":"Texas","abbr":"TX","slug":"beaumont-tx"},
    {"city":"Odessa","state":"Texas","abbr":"TX","slug":"odessa-tx"},
    {"city":"Springfield","state":"Texas","abbr":"TX","slug":"spring-tx"},
    {"city":"Sugar Land","state":"Texas","abbr":"TX","slug":"sugar-land-tx"},
    {"city":"Lewisville","state":"Texas","abbr":"TX","slug":"lewisville-tx"},
    {"city":"League City","state":"Texas","abbr":"TX","slug":"league-city-tx"},
    {"city":"Tyler","state":"Texas","abbr":"TX","slug":"tyler-tx"},
    {"city":"Pearland","state":"Texas","abbr":"TX","slug":"pearland-tx"},
    {"city":"College Station","state":"Texas","abbr":"TX","slug":"college-station-tx"},
    # Utah
    {"city":"Salt Lake City","state":"Utah","abbr":"UT","slug":"salt-lake-city-ut"},
    {"city":"West Valley City","state":"Utah","abbr":"UT","slug":"west-valley-city-ut"},
    {"city":"Provo","state":"Utah","abbr":"UT","slug":"provo-ut"},
    {"city":"West Jordan","state":"Utah","abbr":"UT","slug":"west-jordan-ut"},
    {"city":"Orem","state":"Utah","abbr":"UT","slug":"orem-ut"},
    {"city":"Sandy","state":"Utah","abbr":"UT","slug":"sandy-ut"},
    {"city":"Ogden","state":"Utah","abbr":"UT","slug":"ogden-ut"},
    {"city":"St. George","state":"Utah","abbr":"UT","slug":"st-george-ut"},
    {"city":"Layton","state":"Utah","abbr":"UT","slug":"layton-ut"},
    {"city":"Taylorsville","state":"Utah","abbr":"UT","slug":"taylorsville-ut"},
    # Vermont
    {"city":"Burlington","state":"Vermont","abbr":"VT","slug":"burlington-vt"},
    {"city":"South Burlington","state":"Vermont","abbr":"VT","slug":"south-burlington-vt"},
    {"city":"Rutland","state":"Vermont","abbr":"VT","slug":"rutland-vt"},
    # Virginia
    {"city":"Virginia Beach","state":"Virginia","abbr":"VA","slug":"virginia-beach-va"},
    {"city":"Norfolk","state":"Virginia","abbr":"VA","slug":"norfolk-va"},
    {"city":"Chesapeake","state":"Virginia","abbr":"VA","slug":"chesapeake-va"},
    {"city":"Richmond","state":"Virginia","abbr":"VA","slug":"richmond-va"},
    {"city":"Newport News","state":"Virginia","abbr":"VA","slug":"newport-news-va"},
    {"city":"Alexandria","state":"Virginia","abbr":"VA","slug":"alexandria-va"},
    {"city":"Hampton","state":"Virginia","abbr":"VA","slug":"hampton-va"},
    {"city":"Roanoke","state":"Virginia","abbr":"VA","slug":"roanoke-va"},
    {"city":"Portsmouth","state":"Virginia","abbr":"VA","slug":"portsmouth-va"},
    {"city":"Suffolk","state":"Virginia","abbr":"VA","slug":"suffolk-va"},
    {"city":"Lynchburg","state":"Virginia","abbr":"VA","slug":"lynchburg-va"},
    {"city":"Harrisonburg","state":"Virginia","abbr":"VA","slug":"harrisonburg-va"},
    {"city":"Charlottesville","state":"Virginia","abbr":"VA","slug":"charlottesville-va"},
    {"city":"Manassas","state":"Virginia","abbr":"VA","slug":"manassas-va"},
    # Washington
    {"city":"Seattle","state":"Washington","abbr":"WA","slug":"seattle-wa"},
    {"city":"Spokane","state":"Washington","abbr":"WA","slug":"spokane-wa"},
    {"city":"Tacoma","state":"Washington","abbr":"WA","slug":"tacoma-wa"},
    {"city":"Vancouver","state":"Washington","abbr":"WA","slug":"vancouver-wa"},
    {"city":"Bellevue","state":"Washington","abbr":"WA","slug":"bellevue-wa"},
    {"city":"Kent","state":"Washington","abbr":"WA","slug":"kent-wa"},
    {"city":"Everett","state":"Washington","abbr":"WA","slug":"everett-wa"},
    {"city":"Renton","state":"Washington","abbr":"WA","slug":"renton-wa"},
    {"city":"Kirkland","state":"Washington","abbr":"WA","slug":"kirkland-wa"},
    {"city":"Bellingham","state":"Washington","abbr":"WA","slug":"bellingham-wa"},
    {"city":"Kennewick","state":"Washington","abbr":"WA","slug":"kennewick-wa"},
    {"city":"Yakima","state":"Washington","abbr":"WA","slug":"yakima-wa"},
    {"city":"Redmond","state":"Washington","abbr":"WA","slug":"redmond-wa"},
    {"city":"Federal Way","state":"Washington","abbr":"WA","slug":"federal-way-wa"},
    {"city":"Marysville","state":"Washington","abbr":"WA","slug":"marysville-wa"},
    # West Virginia
    {"city":"Charleston","state":"West Virginia","abbr":"WV","slug":"charleston-wv"},
    {"city":"Huntington","state":"West Virginia","abbr":"WV","slug":"huntington-wv"},
    {"city":"Parkersburg","state":"West Virginia","abbr":"WV","slug":"parkersburg-wv"},
    {"city":"Morgantown","state":"West Virginia","abbr":"WV","slug":"morgantown-wv"},
    # Wisconsin
    {"city":"Milwaukee","state":"Wisconsin","abbr":"WI","slug":"milwaukee-wi"},
    {"city":"Madison","state":"Wisconsin","abbr":"WI","slug":"madison-wi"},
    {"city":"Green Bay","state":"Wisconsin","abbr":"WI","slug":"green-bay-wi"},
    {"city":"Kenosha","state":"Wisconsin","abbr":"WI","slug":"kenosha-wi"},
    {"city":"Racine","state":"Wisconsin","abbr":"WI","slug":"racine-wi"},
    {"city":"Appleton","state":"Wisconsin","abbr":"WI","slug":"appleton-wi"},
    {"city":"Waukesha","state":"Wisconsin","abbr":"WI","slug":"waukesha-wi"},
    {"city":"Oshkosh","state":"Wisconsin","abbr":"WI","slug":"oshkosh-wi"},
    {"city":"Eau Claire","state":"Wisconsin","abbr":"WI","slug":"eau-claire-wi"},
    {"city":"Janesville","state":"Wisconsin","abbr":"WI","slug":"janesville-wi"},
    {"city":"La Crosse","state":"Wisconsin","abbr":"WI","slug":"la-crosse-wi"},
    # Wyoming
    {"city":"Cheyenne","state":"Wyoming","abbr":"WY","slug":"cheyenne-wy"},
    {"city":"Casper","state":"Wyoming","abbr":"WY","slug":"casper-wy"},
    {"city":"Laramie","state":"Wyoming","abbr":"WY","slug":"laramie-wy"},
    {"city":"Gillette","state":"Wyoming","abbr":"WY","slug":"gillette-wy"},
    # DC
    {"city":"Washington","state":"District of Columbia","abbr":"DC","slug":"washington-dc"},
]

# Build lookup dict by slug for fast route resolution
CITY_BY_SLUG = {c["slug"]: c for c in CITIES}
